MODEL:
  WEIGHTS: ''
compute_precision:
  grad_scaler: true
  teacher:
    backbone:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    dino_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    ibot_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    ibot_head_he:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    ibot_head_mx:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    mx_distil_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
  student:
    backbone:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    dino_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp32
        buffer_dtype: fp32
    ibot_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp32
        buffer_dtype: fp32
    ibot_head_he:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    ibot_head_mx:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    mx_distil_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
dino:
  loss_weight: 1.0
  head_n_prototypes: 65536
  head_bottleneck_dim: 256
  head_nlayers: 3
  head_hidden_dim: 2048
  koleo_loss_weight: 0.0
  modality_dropout: 0.7
  kde_loss_weight: 0.05
  kde_loss_parameter: 5.0
ibot:
  loss_weight: 1.0
  mask_sample_probability: 0.5
  mask_ratio_min_max:
  - 0.1
  - 0.5
  separate_head: false
  head_n_prototypes: 65536
  head_bottleneck_dim: 256
  head_nlayers: 3
  head_hidden_dim: 2048
  separate_he_mx_head: false
  cross_modality_masking: true
  mask_ratio_min_max_mm:
  - 0.6
  - 0.9
train:
  batch_size_per_gpu: 28
  dataset_path: ImageNet:split=TRAIN
  output_dir: /capstor/scratch/cscs/bvquerfurth/mmvirtues-outputs/10_29_very_strong_retrain
  saveckp_freq: 20
  seed: 0
  num_workers: 16
  OFFICIAL_EPOCH_LENGTH: 1250
  cache_dataset: true
  centering: sinkhorn_knopp
student:
  arch: vit_large
  patch_size: 14
  drop_path_rate: 0.1
  layerscale: 1.0e-05
  drop_path_uniform: true
  pretrained_weights: ''
  ffn_layer: swiglu
  block_chunks: 0
  qkv_bias: true
  proj_bias: true
  ffn_bias: true
  num_register_tokens: 4
  interpolate_antialias: false
  interpolate_offset: 0.1
  feedforward_dim: 5472
  num_encoder_heads: 16
teacher:
  momentum_teacher: 0.992
  final_momentum_teacher: 1
  warmup_teacher_temp: 0.04
  teacher_temp: 0.07
  warmup_teacher_temp_epochs: 30
optim:
  epochs: 100
  weight_decay: 0.04
  weight_decay_end: 0.4
  base_lr: 0.004
  lr: 0.0052915026221291815
  warmup_epochs: 10
  min_lr: 1.0e-06
  clip_grad: 3.0
  freeze_last_layer_epochs: 1
  scaling_rule: sqrt_wrt_1024
  patch_embed_lr_mult: 0.2
  layerwise_decay: 0.9
  adamw_beta1: 0.9
  adamw_beta2: 0.999
crops:
  global_crops_scale:
  - 0.48
  - 1.0
  local_crops_number: 8
  local_crops_scale:
  - 0.16
  - 0.48
  global_crops_size: 224
  local_crops_size: 98
  crops_all_same_chs: false
  unalign_local_crops: 0
evaluation:
  eval_period_iterations: 12500
experiment:
  name: 10_29_very_strong_retrain
  description: DinoV2 with Virtues as Tokenizer
  dir: /capstor/scratch/cscs/bvquerfurth/mmvirtues-outputs
  log_dir: logs
  checkpoint_dir: checkpoints
  wandb_entity: mmVirtues
  wandb_project: mmVirTues_Oct2025
  wandb_run_id: null
  wandb_mode: online
marker_embedding_dir: /datasets/marker_embeddings/esm2_t30_150M_UR50D
cords_downstream_cfg: /mmvirtues/dinov2/configs/datasets/swissai_configs/cords24.yaml
orion_downstream_cfg: /mmvirtues/dinov2/configs/datasets/swissai_configs/orion.yaml
hibou_weights: /capstor/store/cscs/swissai/a146/model_ckpts/hibou/hibou-l/hibou-l_timm_format.pth
model_weights:
  imagenet: false
  uni: false
  dino_cords_imc: false
  dino_sp: false
image_info:
  patch_size: 14
  rnd_crop_size: 256
  use_rnd_crop_dir: true
  use_fraction_training: 1.0
  image_section_size:
  - 256
  - 256
  mask_ratio:
  - 0.6
  - 1.0
  mask_strategy: uniform_independent
  channel_fraction:
  - 1.0
  - 1.0
  local_crops_channel_ratio:
  - 0.75
  - 0.9
  global_crops_channel_ratio:
  - 0.75
  - 0.9
  num_channels_to_full_mask: null
  num_channels_to_keep: null
  stride: null
  crop_strategy: random_crops
  normalization: q_99
  use_fixed_drop_range: false
  apply_gaussian: true
  apply_median: true
  balance_modalities: true
  include_clusters: false
  do_hed_augmentation: true
  dataset_distribution_alpha: 0.5
model:
  pos_emb: rope
  model_dim: 1024
  feedforward_dim: 2048
  encoder_pattern: vv
  num_encoder_heads: 8
  dropout: 0.0
  unfreeze_after_steps: 0
  separate_encoders: false
  separate_decoders: false
  psAttn_posemb_once: false
  group_layers: true
  norm_after_encoder_decoder: true
  norm_after_he_tokenizer: true
  use_technology_emb: false
